# Generated by Django 4.0.1 on 2022-01-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
